# Example of usage of the instance and solution validators 

This notebook assumes that https://co2020-ba-vu.challenges.ortec.com/zips/Validator.zip has been unpacked to a subdirectory of the current directory called `ParticipantsSuite`, changes to a different location are obvious. 

It also assumes a subdirectory `instances` containing the instance files. 

In [1]:
import sys
import os
sys.path.append('./ParticipantsSuite')

from InstanceCVRPTWUI import InstanceCVRPTWUI
from SolutionCVRPTWUI import SolutionCVRPTWUI

Assuming that what you mean by 'how to use the code of the VeroLog solver?' is actually a question about the instance and solution validators, please find examples below. 

In [2]:
instance = InstanceCVRPTWUI('instances/ORTEC_Test_01.txt')

if instance.isValid():
    instance.calculateDistances()
    import numpy
    nLoc = len(instance.Coordinates)
    C = numpy.asarray( [ [ instance.calcDistance[i][j] for j in range(nLoc) ] for i in range(nLoc) ] )

    print(C)
    
    for t in instance.Tools:
        print(t)
    for c in instance.Coordinates:
        print(c)
    for r in instance.Requests:
        print(r)

[[   0 3488 3945 ... 3273 3557 3782]
 [3488    0 3268 ... 2747 3251 3586]
 [3945 3268    0 ...  715  442  513]
 ...
 [3273 2747  715 ...    0  511  850]
 [3557 3251  442 ...  511    0  339]
 [3782 3586  513 ...  850  339    0]]
1	2	280	10000
2	14	135	10000
0	5445	2890
1	4275	6176
2	7543	6232
3	6788	6348
4	7867	6402
5	6918	6441
6	6812	6463
7	3366	6496
8	7480	6561
9	8197	6594
10	7699	6674
11	7022	6693
12	3979	6765
13	3698	6826
14	4245	6835
15	4281	4251
16	4797	7038
17	4382	7144
18	8665	7168
19	6733	7175
20	3936	7201
21	3919	7301
22	7667	7301
23	8214	7316
24	3845	7358
25	7097	7417
26	7309	7458
27	4211	7472
28	7038	7545
29	7367	7549
30	7913	7601
31	7905	7615
32	6507	7633
33	6659	7747
34	7400	7892
35	8364	7936
36	4328	7959
37	8468	7997
38	7313	8064
39	7161	8069
40	9984	8101
41	7549	8106
42	7294	8201
43	9802	8218
44	6472	8233
45	7505	4478
46	6742	8297
47	7634	8349
48	5487	8510
49	6334	8437
50	5884	8471
51	6748	8525
52	9691	8533
53	6396	6539
54	9405	8733
55	5992	2562
56	8103	8828
57	7065	8965

Now let us assume that you write your solution to `ORTEC_Test_01.sol`. 
You may validate your solution with the code below.
Note that the very last line writes a new file, called `ORTEC_Test_01.extra.sol`, as described on the section **Extra information in the solution text file** at page 6 of https://co2020-ba-vu.challenges.ortec.com/pdf/Challenge_problem.pdf

In [3]:
solution = SolutionCVRPTWUI('ORTEC_Test_01.sol',instance,continueOnErr=True)
if not solution.isValid():
    print('errors:')
    print('\n'.join(solution.errorReport))
    print('warnings:')
    print('\n'.join(solution.warningReport))
solution.writeSolution('ORTEC_Test_01.extra.sol',True)

Solution file written to ORTEC_Test_01.extra.sol
